"use strict";
exports.__esModule = true;
exports.b8 = exports.b7 = exports.c6 = exports.b6 = exports.b5 = void 0;
var b5 = [
    'Biacsi Katalin',
    'Domonkos Bence',
    'Fábián Kornél',
    'Fábián Patrik Dominik',
    'Farkas Botond Vince',
    'Fodor Andrea Rita',
    'Grund Fanni',
    'Gyuricsek Réka Tímea',
    'Kneip Bálint Dániel',
    'Kovács Jázmin',
    'Kovács Kristóf Péter',
    'Makra Izabella',
    'Mazurák Márk',
    'Molnár Liliána',
    'Német Viktor',
    'Németh Dóra',
    'Nothof Abigél',
    'Nothof Bence',
    'Perneki Zsombor',
    'Széll Sebestyén',
    'Temesvári Regina',
    'Temesvári Szabolcs',
    'Telek Boglárka',
    'Tulman -Fischer Alex',
    'Vajna Eliza',
    'Zákány Barnabás',
];
exports.b5 = b5;
var b6 = [
    'Ambrus Petra',
    'Benke Krisztina',
    'Borsodi-Kalmár Gréta',
    'Böjti Maja',
    'Czabai Kira',
    'Csajkás Maja',
    'Gulyás Adél',
    'Gyurcsik Máté',
    'Hegyi László',
    'Horgos Dániel',
    'Juhász Milla',
    'Kecskés Dorottya',
    'Makra Mihály',
    'Moczó Csenge',
    'Molnár Dóra',
    'Nyerges Kata Hanna',
    'Nyilas Dániel',
    'Pataki Csenge',
    'Szalai Niraj Noel',
    'Temesvári Gábor',
    'Széll Bendegúz',
    'Tornyi Olivér',
    'Zakar Zsolna',
];
exports.b6 = b6;
var c6 = [
    'Balogh Edgár',
    'Becsek Enikő',
    'Belovai Nedda',
    'Boldizsár Réka',
    'Csányi Botond Ferenc',
    'Dancsik Antónia',
    'Felföldi Ádám',
    'Ficzere Hédi',
    'Füle Lilla',
    'Gargács-Acsai Gergő',
    'Herczeg Kincső',
    'Kabók Nelli Julianna',
    'Kertész Lívia',
    'Kovács Jázmin',
    'Mihály Brigitta',
    'Molnár Dorina',
    'Óvári Noémi',
    'Papdi Levente',
    'Sándor Máté',
    'Tóth István Mihály',
    'Várhelyi Levente',
    'Zsoldos Zoltán',
];
exports.c6 = c6;
var b7 = [
    'Ács Emese',
    'Bálint-Harmati Linett',
    'Berek Csaba',
    'Czentye Botond József',
    'Csiszér Barnabás',
    'Dékány Attila',
    'Erdélyi Balázs András',
    'Farkas Flóra Dóra',
    'Fodor Angelika',
    'Győrfi Gábor',
    'Kovács Tamás',
    'Kőházi Dalma Mira',
    'Miklós Milla',
    'Molnár Viktória Noémi',
    'Molnár Zengő',
    'Nagy Leonóra',
    'Nyerges Emese Anna',
    'Nyilas Réka Róza',
    'Perneki Dóra',
    'Szabó Boglárka',
    'Takács Máté',
    'Temkó Kata Kitti',
    'Tóth Tamás Ádám',
];
exports.b7 = b7;
var b8 = [
    'Bodó Lilla',
    'Csúri Zsuzsa',
    'Dudás Zsombor Zsolt',
    'Fábián Réka ',
    'Gubacsi Réka',
    'Izbéki Lőrinc',
    'Juhász Alex',
    'Juhász Olivér',
    'Kertész Mihály',
    'Kiss Gergő Attila',
    'Kiss Virág Fanni',
    'Kovács Martin Tamás',
    'Matovics Alex',
    'Matovics Ivett',
    'Moczó Gréta',
    'Molnár Csinszka',
    'Nagy Anna Sára',
    'Németh Sarolta',
    'Pataki Kolos',
    'Sárkány Kitti',
    'Süli Szilveszter',
    'Szőke Dominik Gergő',
    'Szutor Alex',
    'Teiszler Bence',
    'Teiszler Tamás',
    'Tóth Boglárka',
    'Tóth Fruzsina Réka',
    'Tóth Nimród',
    'Zakar Zsolt',
];
exports.b8 = b8;
